baseURL         = 'https://orikama.github.io'
languageCode    = 'en-us'
title           = 'Vladimir Matushkin'

# For search functionality
[outputs]
  home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"]

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
